# Generated by Django 2.0.3 on 2018-03-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animation',
            name='size_h',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='animation',
            name='size_w',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
