# Generated by Django 2.0.3 on 2018-03-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180323_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='path',
            field=models.CharField(blank=True, default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animation',
            name='size_h',
            field=models.CharField(blank=True, default='default', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animation',
            name='size_w',
            field=models.CharField(blank=True, default='default', max_length=5),
            preserve_default=False,
        ),
    ]
